### ISSUE TITLE
Welcome to a June GitHub for Developers class!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-group-june#1]
Hello Group! 👋 

Use this issue to add your comments and hopes about this class. If you have any long standing questions you can also open additional issues for us to look at.
## TODO
- [x] Create issue
- [ ] Wait for comments
- [ ] Add commenters as collaborators

cc @stoe so you are explicitly subscribed to this thread

**Comment by stoe** [comment]
:wave: @githubteacher 

Thanks for the cc.

**Comment by r-daga** [comment]
Hello GitHub!

**Comment by balakondepudi** [comment]
Hello Github.
Thanks @stoe @githubteacher

**Comment by githubteacher** [comment]
:tada: @r-daga and @balakondepudi are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
💪 @r-daga for being first! ✨

**Comment by sujan792000** [comment]
hello

**Comment by Dushyant4** [comment]
Hello Github

**Comment by githubteacher** [comment]
:tada: @sujan792000 and @Dushyant4 are now  repository collaborators. :balloon:

**Comment by midimonkey** [comment]
Ca va

**Comment by githubteacher** [comment]
:tada: @midimonkey is now a repository collaborator. :balloon:

**Comment by superdev567** [comment]
Im here! :)

**Comment by githubteacher** [comment]
:tada: @superdev567 is now a repository collaborator. :balloon:
